"""
tools/ppt_generator.py — Automated Executive Briefing Engine

Generates a fully-styled PowerPoint presentation representing the codebase,
including dynamic injection of Mermaid diagrams, security diffs, and
presenter notes (speaker script) for each slide.
"""

import os
import base64
import requests
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.enum.text import PP_ALIGN


def _download_mermaid_image(mermaid_text: str, output_path: str):
    """
    Renders Mermaid JS to a PNG using mermaid.ink, which is an open API.
    """
    try:
        # Mermaid.ink expects base64 encoded graph
        graph_bytes = mermaid_text.encode("utf-8")
        base64_bytes = base64.b64encode(graph_bytes)
        base64_string = base64_bytes.decode("utf-8")
        
        url = f"https://mermaid.ink/img/{base64_string}"
        response = requests.get(url)
        
        if response.status_code == 200:
            with open(output_path, 'wb') as f:
                f.write(response.content)
            return True
    except Exception as e:
        print(f"[PPT Generator] Failed to download Mermaid diagram: {e}")
    return False


def _add_speaker_notes(slide, notes: str):
    """Adds a script to the presenter notes section of the slide."""
    notes_slide = slide.notes_slide
    text_frame = notes_slide.notes_text_frame
    text_frame.text = notes


def generate_executive_briefing(
    repo_name: str,
    architecture_info: dict,
    security_info: dict,
    business_info: dict,
    output_filepath: str = "Codebase_Executive_Briefing.pptx"
):
    """
    Generates the Executive Briefing PPT.
    """
    prs = Presentation()
    
    # 1. Title Slide
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    title = slide.shapes.title
    subtitle = slide.placeholders[1]
    
    title.text = f"{repo_name} - Codebase Analysis"
    subtitle.text = "Generated by Carbon DevRel Engine"
    
    _add_speaker_notes(slide, f"Welcome to the architectural review and security briefing for the {repo_name} repository.")
    
    # 2. Executive Summary Slide
    bullet_slide_layout = prs.slide_layouts[1]
    slide = prs.slides.add_slide(bullet_slide_layout)
    shapes = slide.shapes
    title_shape = shapes.title
    body_shape = shapes.placeholders[1]
    
    title_shape.text = "Executive Summary"
    tf = body_shape.text_frame
    tf.text = architecture_info.get("summary", "App purpose not found.")
    
    # Add business flows
    for flow in business_info.get("business_flows", [])[:3]:
        p = tf.add_paragraph()
        p.text = f"Key Flow: {flow.get('feature')}"
        p.level = 1
        
    _add_speaker_notes(slide, "At a high level, this application handles the following core business flows.")

    # 3. Architecture Diagram Slide
    diagram_slide_layout = prs.slide_layouts[5] # Title only
    slide = prs.slides.add_slide(diagram_slide_layout)
    slide.shapes.title.text = "System Architecture"
    
    mermaid_code = architecture_info.get("diagram", "")
    if mermaid_code:
        # strip markdown blocks if they exist
        mermaid_code = mermaid_code.replace("```mermaid", "").replace("```", "").strip()
        temp_img_path = "temp_architecture.png"
        
        success = _download_mermaid_image(mermaid_code, temp_img_path)
        if success:
            # Add image to slide, centered
            try:
                slide.shapes.add_picture(temp_img_path, Inches(1), Inches(2), width=Inches(8))
                os.remove(temp_img_path)
            except Exception as e:
                print(f"Error adding picture to PPT: {e}")
        else:
            tf = slide.shapes.add_textbox(Inches(1), Inches(2), Inches(8), Inches(4)).text_frame
            tf.text = "Failed to render Mermaid diagram."
            
    _add_speaker_notes(slide, "Here is the dynamic architecture diagram. As you can see, the components interact smoothly. Notice the central database connections.")
    
    # 4. Security Blast Radius Slide
    slide = prs.slides.add_slide(bullet_slide_layout)
    slide.shapes.title.text = "DevSecOps Scorecard"
    tf = slide.shapes.placeholders[1].text_frame
    
    scorecard = security_info.get("scorecard", {})
    tf.text = f"Security Grade: {scorecard.get('grade', 'N/A')}"
    
    p = tf.add_paragraph()
    p.text = f"Critical Vulnerabilities: {scorecard.get('critical', 0)}"
    p.level = 1
    
    p = tf.add_paragraph()
    p.text = f"High Vulnerabilities: {scorecard.get('high', 0)}"
    p.level = 1
    
    findings = security_info.get("findings", [])
    if findings:
        p = tf.add_paragraph()
        p.text = f"Top Finding: {findings[0]['title']} in {findings[0]['filePath']}"
        p.level = 1
        
    _add_speaker_notes(slide, "We ran 50+ CWE-mapped rules against the codebase. Here are the DevSecOps results.")

    prs.save(output_filepath)
    print(f"[PPT Generator] Executive Briefing saved to {output_filepath}")
    return output_filepath

