// ============================================================
//  routes/explainVideo.js
//
//  Handles the /api/explain-video endpoint.
//  Acts as the MCP client adapter for Scrimba.
//
//  Features:
//  - #5 Error Recovery: splits oversized OPML into ≤60 KB
//    chunks so it never exceeds Scrimba's 64 KB per-chunk limit.
//  - #6 Retry Logic: every Scrimba MCP call goes through
//    scrimbaCall(), which retries up to MAX_RETRIES times with
//    exponential back-off on transient network/server errors.
// ============================================================

const express = require('express');
const axios   = require('axios');
const router  = express.Router();

const PYTHON_SERVICE_URL = (process.env.PYTHON_SERVICE_URL || 'http://localhost:8000').trim().replace(/\/+$/, '');
const SCRIMBA_MCP_URL    = 'https://scrimba.com/mcp/explain';

const SCRIMBA_HEADERS = {
  'Content-Type': 'application/json',
  'Accept': 'application/json, text/event-stream'
};

// ── #5: OPML chunk size limit ────────────────────────────────
// Scrimba enforces 64 000 bytes per append_explainer_chunk call.
// We target 60 000 bytes to stay safely under the ceiling.
const CHUNK_MAX_BYTES = 60_000;

// ── #6: Retry configuration ──────────────────────────────────
const MAX_RETRIES      = 3;
const RETRY_BASE_MS    = 1_500; // first back-off delay

/**
 * Wraps an axios POST to the Scrimba MCP with retry logic.
 *
 * Retries on:
 *  - Network-level errors (ECONNRESET, ETIMEDOUT, etc.)
 *  - HTTP 5xx responses from Scrimba
 *
 * Does NOT retry on:
 *  - jsonrpc-level errors returned inside a 200 response body
 *    (those represent logic errors, not transient failures)
 *
 * @param {object} payload  - JSON-RPC payload
 * @param {string} label    - Human-readable label for log messages
 * @returns {object}        - The parsed axios response data
 */
async function scrimbaCall(payload, label) {
  let lastError;

  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    try {
      console.log(`📡 [${label}] attempt ${attempt}/${MAX_RETRIES}…`);
      const response = await axios.post(SCRIMBA_MCP_URL, payload, {
        headers: SCRIMBA_HEADERS,
        timeout: 30_000 // 30 s per MCP call
      });

      // 5xx from Scrimba's HTTP layer → treat as transient
      if (response.status >= 500) {
        throw new Error(`Scrimba returned HTTP ${response.status}`);
      }

      console.log(`✅ [${label}] succeeded on attempt ${attempt}.`);
      return response.data;

    } catch (err) {
      lastError = err;
      const isTransient =
        err.code === 'ECONNRESET'   ||
        err.code === 'ETIMEDOUT'    ||
        err.code === 'ECONNABORTED' ||
        (err.response && err.response.status >= 500);

      if (!isTransient || attempt === MAX_RETRIES) {
        console.error(`❌ [${label}] failed after ${attempt} attempt(s):`, err.message);
        break;
      }

      const delayMs = RETRY_BASE_MS * Math.pow(2, attempt - 1); // 1.5 s, 3 s, 6 s
      console.warn(`⚠️  [${label}] attempt ${attempt} failed (${err.message}). Retrying in ${delayMs}ms…`);
      await new Promise(resolve => setTimeout(resolve, delayMs));
    }
  }

  throw lastError;
}

/**
 * Splits an OPML string into UTF-8–safe chunks of at most
 * CHUNK_MAX_BYTES bytes each.
 *
 * We split on newline boundaries so we never cut in the middle
 * of a multi-byte character or an OPML tag.
 *
 * @param {string} opml
 * @returns {string[]}
 */
function splitIntoChunks(opml) {
  const lines  = opml.split('\n');
  const chunks = [];
  let current  = '';

  for (const line of lines) {
    const candidate = current ? current + '\n' + line : line;
    if (Buffer.byteLength(candidate, 'utf8') > CHUNK_MAX_BYTES) {
      // Flush the current accumulator and start a new one with this line
      if (current) chunks.push(current);
      current = line;
    } else {
      current = candidate;
    }
  }
  if (current) chunks.push(current);

  return chunks;
}

// ── Main route ───────────────────────────────────────────────
router.post('/explain-video', async (req, res) => {
  const { architecture, apiDocs, businessLogic } = req.body;
  console.log('🎥 Received explain-video request.');

  try {
    // ── Step 1: Open explainer stream ──────────────────────────
    const startData = await scrimbaCall(
      {
        jsonrpc: '2.0',
        id: Date.now(),
        method: 'tools/call',
        params: {
          name: 'start_explainer_stream',
          arguments: {
            title: 'Carbon Codebase Video Explanation',
            description: 'An interactive codebase explanation generated by Carbon.',
            visibility: 'unlisted'
          }
        }
      },
      'start_explainer_stream'
    );

    if (startData.error) {
      console.error('❌ Scrimba MCP error on start:', startData.error);
      return res.status(500).json({ error: 'Failed to initialize video stream on Scrimba.', details: startData.error });
    }

    const contentText = startData.result?.content?.[0]?.text;
    if (!contentText) {
      console.error('❌ Scrimba start returned empty content:', startData);
      return res.status(500).json({ error: 'Empty response from Scrimba MCP.' });
    }

    const urlMatch   = contentText.match(/https:\/\/scrimba\.com\/explain\/[^\s]+/);
    const tokenMatch = contentText.match(/stream_token:\s*([a-zA-Z0-9_]+)/);
    const shareUrl   = urlMatch   ? urlMatch[0]   : null;
    const streamToken = tokenMatch ? tokenMatch[1] : null;

    if (!shareUrl || !streamToken) {
      console.error('❌ Could not parse session URL / token from Scrimba response.');
      return res.status(500).json({ error: 'Failed to parse session details from Scrimba.' });
    }
    console.log(`   Token: ${streamToken}  |  URL: ${shareUrl}`);

    // ── Step 2: Generate OPML via Python agent ─────────────────
    console.log('🐍 Calling Python agent service to generate OPML explanation…');
    const opmlRes = await axios.post(
      `${PYTHON_SERVICE_URL}/generate-explainer-opml`,
      { architecture, api_docs: apiDocs, business_logic: businessLogic },
      { timeout: 120_000 }
    );

    if (!opmlRes.data?.success || !opmlRes.data?.opml) {
      console.error('❌ Python service failed to generate OPML:', opmlRes.data);
      return res.status(500).json({ error: 'Python agent service failed to generate explanation.' });
    }

    const opmlMarkup  = opmlRes.data.opml;
    const totalBytes  = Buffer.byteLength(opmlMarkup, 'utf8');
    console.log(`✅ OPML generated (${totalBytes} bytes).`);

    // ── Step 3: Append OPML in chunks (#5 Error Recovery) ─────
    const chunks = splitIntoChunks(opmlMarkup);
    console.log(`📦 Splitting into ${chunks.length} chunk(s) (max ${CHUNK_MAX_BYTES} bytes each).`);

    for (let i = 0; i < chunks.length; i++) {
      const chunkBytes = Buffer.byteLength(chunks[i], 'utf8');
      console.log(`   Sending chunk ${i + 1}/${chunks.length} (${chunkBytes} bytes)…`);

      const appendData = await scrimbaCall(
        {
          jsonrpc: '2.0',
          id: Date.now() + i + 1,
          method: 'tools/call',
          params: {
            name: 'append_explainer_chunk',
            arguments: { stream_token: streamToken, opml: chunks[i] }
          }
        },
        `append_explainer_chunk [${i + 1}/${chunks.length}]`
      );

      if (appendData.error) {
        console.error(`❌ Scrimba MCP error on chunk ${i + 1}:`, appendData.error);
        return res.status(500).json({
          error: `Failed to push chunk ${i + 1} to Scrimba.`,
          details: appendData.error
        });
      }

      // Log remaining budget from Scrimba's response
      const budget = appendData.result?.structuredContent;
      if (budget?.bytes_remaining !== undefined) {
        console.log(`   Budget remaining: ${budget.bytes_remaining} bytes.`);
      }
    }

    // ── Step 4: Finalize the stream ────────────────────────────
    const finishData = await scrimbaCall(
      {
        jsonrpc: '2.0',
        id: Date.now() + chunks.length + 1,
        method: 'tools/call',
        params: {
          name: 'finish_explainer_stream',
          arguments: { stream_token: streamToken }
        }
      },
      'finish_explainer_stream'
    );

    if (finishData.error) {
      console.error('❌ Scrimba MCP error on finish:', finishData.error);
      return res.status(500).json({ error: 'Failed to finalize video on Scrimba.', details: finishData.error });
    }

    console.log('🎉 Explainer video successfully finished on Scrimba.');
    res.json({ success: true, url: shareUrl });

  } catch (error) {
    console.error('❌ Exception in explain-video endpoint:', error.message);
    res.status(500).json({
      error: 'An unexpected error occurred during video generation.',
      details: error.message
    });
  }
});

module.exports = router;
