// ============================================================
//  routes/explainVideo.js
//
//  Handles the /api/explain-video endpoint.
//  Acts as the MCP client adapter for Scrimba.
// ============================================================

const express = require('express');
const axios = require('axios');
const router = express.Router();

const PYTHON_SERVICE_URL = process.env.PYTHON_SERVICE_URL || 'http://localhost:8000';
const SCRIMBA_MCP_URL = 'https://scrimba.com/mcp/explain';

const SCRIMBA_HEADERS = {
  'Content-Type': 'application/json',
  'Accept': 'application/json, text/event-stream'
};

router.post('/explain-video', async (req, res) => {
  const { architecture, apiDocs, businessLogic } = req.body;

  console.log('🎥 Received explain-video request.');

  try {
    // Step 1: Start the explainer stream on Scrimba MCP
    console.log('📡 Calling start_explainer_stream on Scrimba MCP...');
    const startPayload = {
      jsonrpc: '2.0',
      id: Date.now(),
      method: 'tools/call',
      params: {
        name: 'start_explainer_stream',
        arguments: {
          title: 'Carbon Codebase Video Explanation',
          description: 'An interactive codebase explanation generated by Carbon.',
          visibility: 'unlisted'
        }
      }
    };

    const startRes = await axios.post(SCRIMBA_MCP_URL, startPayload, { headers: SCRIMBA_HEADERS });
    
    if (startRes.data.error) {
      console.error('❌ Scrimba MCP returned an error during start:', startRes.data.error);
      return res.status(500).json({ error: 'Failed to initialize video stream on Scrimba.', details: startRes.data.error });
    }

    const contentText = startRes.data.result?.content?.[0]?.text;
    if (!contentText) {
      console.error('❌ Scrimba MCP response was empty:', startRes.data);
      return res.status(500).json({ error: 'Empty response from Scrimba MCP.' });
    }

    // Extract claim URL and stream token from text
    const urlMatch = contentText.match(/https:\/\/scrimba\.com\/explain\/[^\s]+/);
    const tokenMatch = contentText.match(/stream_token:\s*([a-zA-Z0-9_]+)/);

    const shareUrl = urlMatch ? urlMatch[0] : null;
    const streamToken = tokenMatch ? tokenMatch[1] : null;

    if (!shareUrl || !streamToken) {
      console.error('❌ Failed to parse session details from Scrimba response text.');
      return res.status(500).json({ error: 'Failed to parse session details from Scrimba.', text: contentText });
    }

    console.log(`✅ Session opened. Token: ${streamToken}, URL: ${shareUrl}`);

    // Step 2: Request OPML generation from Python FastAPI Agent Service
    console.log('🐍 Calling Python agent service to generate OPML explanation...');
    const opmlRes = await axios.post(`${PYTHON_SERVICE_URL}/generate-explainer-opml`, {
      architecture,
      api_docs: apiDocs,
      business_logic: businessLogic
    }, { timeout: 120000 }); // 2 minutes timeout for LLM generation

    if (!opmlRes.data?.success || !opmlRes.data?.opml) {
      console.error('❌ Python service failed to generate OPML:', opmlRes.data);
      return res.status(500).json({ error: 'Python agent service failed to generate explanation.' });
    }

    const opmlMarkup = opmlRes.data.opml;
    console.log(`✅ OPML generated successfully (size: ${Buffer.byteLength(opmlMarkup)} bytes).`);

    // Step 3: Append the OPML chunk to Scrimba MCP
    console.log('📡 Appending OPML chunk to Scrimba MCP...');
    const appendPayload = {
      jsonrpc: '2.0',
      id: Date.now() + 1,
      method: 'tools/call',
      params: {
        name: 'append_explainer_chunk',
        arguments: {
          stream_token: streamToken,
          opml: opmlMarkup
        }
      }
    };

    const appendRes = await axios.post(SCRIMBA_MCP_URL, appendPayload, { headers: SCRIMBA_HEADERS });

    if (appendRes.data.error) {
      console.error('❌ Scrimba MCP returned an error during append:', appendRes.data.error);
      return res.status(500).json({ error: 'Failed to push video content to Scrimba.', details: appendRes.data.error });
    }

    console.log('✅ OPML chunk appended.');

    // Step 4: Finalize the stream on Scrimba MCP
    console.log('📡 Calling finish_explainer_stream on Scrimba MCP...');
    const finishPayload = {
      jsonrpc: '2.0',
      id: Date.now() + 2,
      method: 'tools/call',
      params: {
        name: 'finish_explainer_stream',
        arguments: {
          stream_token: streamToken
        }
      }
    };

    const finishRes = await axios.post(SCRIMBA_MCP_URL, finishPayload, { headers: SCRIMBA_HEADERS });

    if (finishRes.data.error) {
      console.error('❌ Scrimba MCP returned an error during finish:', finishRes.data.error);
      return res.status(500).json({ error: 'Failed to finalize video explanation on Scrimba.', details: finishRes.data.error });
    }

    console.log('🎉 Explainer video successfully finished on Scrimba.');

    // Return the URL
    res.json({
      success: true,
      url: shareUrl
    });

  } catch (error) {
    console.error('❌ Exception in explain-video endpoint:', error.message);
    res.status(500).json({
      error: 'An unexpected error occurred during video generation.',
      details: error.message
    });
  }
});

module.exports = router;
